log:
  log_dir: 'log'
  chkpt_dir: 'chkpt'


arcface:
  chkpt_path: 'preprocess/model_mobilefacenet.pth'
  vector_size: 512

data:
  dataset_dir: '/data/jdq/face_dataset/faceshiter/FFHQ'
  valset_dir: '/data/jdq/face_dataset/faceshiter/FFHQ'

model:
  learning_rate_E_G: 4e-4
  learning_rate_D: 4e-4

  beta1: 0
  beta2: 0.999

  batch_size: 8

  num_workers: 40
  grad_clip: 0.0
